name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simular deploy
        run: echo "Desplegando a staging..."

      - name: Crear Issue si falla
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "❌ Falló el deployment"
          content-filepath: ./docs/deploy-error.md
          labels: error, ci
